// 
//  Shell.cs (generated by template)
//  
//  Author:
//       Simon Mika <smika@hx.se>
//  
//  Copyright (c) 2011 Simon Mika
// 
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
// 
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
// 
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System;
using Kean.Core.Extension;

namespace Kean.Math.Geometry2D.Double
{
	public struct Shell :
		IEquatable<Shell>
	{
		public double Left;
		public double Right;
		public double Top;
		public double Bottom;
		public Point LeftTop { get { return new Point(this.Left, this.Top); } }
		public Size Size { get { return new Size(this.Left + this.Right, this.Top + this.Bottom); } }
		public Point Balance { get { return new Point(this.Right - this.Left, this.Bottom - this.Top); } }
		public bool IsZero { get { return this.Left == 0 && this.Right == 0 && this.Top == 0 && this.Bottom == 0; } }
		public bool NotZero { get { return this.Left != 0 && this.Right != 0 && this.Top != 0 && this.Bottom != 0; } }
	  
		public Shell(double value) : this(value, value) { }
		public Shell(double x, double y) : this(x, x, y, y) { }
		public Shell(double left, double right, double top, double bottom)
		{
			this.Left = left;
			this.Right = right;
			this.Top = top;
			this.Bottom = bottom;
		}
		#region Increase, Decrease
		public Box Decrease(Size size)
		{
			return new Box(this.Left, this.Top, size.Width - this.Left - this.Right, size.Height - this.Top - this.Bottom);
		}
		public Box Increase(Size size)
		{
			return  new Box(-this.Left, -this.Right, size.Width + this.Left + this.Right, size.Height + this.Top + this.Bottom);
		}
		public Box Decrease(Box  box)
		{
			return new Box(box.LeftTop.X + this.Left, box.LeftTop.Y + this.Top, box.Size.Width - this.Left - this.Right, box.Size.Height - this.Top - this.Bottom);
		}
		public Box Increase(Box box)
		{
			return new Box(box.LeftTop.X - this.Left, box.LeftTop.Y - this.Top, box.Size.Width + this.Left + this.Right, box.Size.Height + this.Top + this.Bottom);
		}
		#endregion
		#region Static Operators
		public static Size operator -(Size left, Shell right)
		{
			return new Size(left.Width - right.Left - right.Right, left.Height - right.Top - right.Bottom);
		}
		public static Size operator +(Size left, Shell right)
		{
			return new Size(left.Width + right.Left + right.Right, left.Height + right.Top + right.Bottom);
		}
		public static Shell operator +(Shell left, Shell right)
		{
			return new Shell(left.Left + right.Left, left.Right + right.Right, left.Top + right.Top, left.Bottom + right.Bottom);
		}
		public static Shell operator -(Shell left, Shell right)
		{
			return new Shell(left.Left - right.Left, left.Right - right.Right, left.Top - right.Top, left.Bottom - right.Bottom);
		}
		public static Shell Maximum(Shell left, Shell right)
		{
			return new Shell(Kean.Math.Double.Maximum(left.Left, right.Left), Kean.Math.Double.Maximum(left.Right, right.Right), Kean.Math.Double.Maximum(left.Top, right.Top), Kean.Math.Double.Maximum(left.Bottom, right.Bottom));
		}
		public static Shell Minimum(Shell left, Shell right)
		{
			return new Shell(Kean.Math.Double.Minimum(left.Left, right.Left), Kean.Math.Double.Minimum(left.Right, right.Right), Kean.Math.Double.Minimum(left.Top, right.Top), Kean.Math.Double.Minimum(left.Bottom, right.Bottom));
		}
		#endregion
		#region Comparison Operators
		/// <summary>
		/// Defines equality.
		/// </summary>
		/// <param name="Left">Point Left of operator.</param>
		/// <param name="Right">Point Right of operator.</param>
		/// <returns>True if <paramref name="Left"/> equals <paramref name="Right"/> else false.</returns>
		public static bool operator ==(Shell left, Shell right)
		{
			return left.Left == right.Left && left.Right == right.Right && left.Top == right.Top && left.Bottom == right.Bottom;
		}
		/// <summary>
		/// Defines inequality.
		/// </summary>
		/// <param name="Left">Point Left of operator.</param>
		/// <param name="Right">Point Right of operator.</param>
		/// <returns>False if <paramref name="Left"/> equals <paramref name="Right"/> else true.</returns>
		public static bool operator !=(Shell left, Shell right)
		{
			return !(left == right);
		}
		#endregion
		#region Casts
		public static implicit operator Shell(Single.Shell value)
		{
			return new Shell(value.Left, value.Right, value.Top, value.Bottom);
		}
		public static implicit operator Shell(Integer.Shell value)
		{
			return new Shell(value.Left, value.Right, value.Top, value.Bottom);
		}
		public static explicit operator Single.Shell(Shell value)
		{
			return new Single.Shell((float)value.Left, (float)value.Right, (float)value.Top, (float)value.Bottom);
		}
		public static explicit operator Integer.Shell(Shell value)
		{
			return new Integer.Shell((int)value.Left, (int)value.Right, (int)value.Top, (int)value.Bottom);
		}
		public static implicit operator string(Shell value)
		{
			return value.NotNull() ? value.ToString() : null;
		}
		public static explicit operator Shell(string value)
		{
			Shell result = new Shell();
			if (value.NotEmpty())
			{
				try
				{
					string[] values = value.Split(new char[] { ',', ' ' }, StringSplitOptions.RemoveEmptyEntries);
					if (values.Length == 4)
						result = new Shell(Kean.Math.Double.Parse(values[0]), Kean.Math.Double.Parse(values[1]), Kean.Math.Double.Parse(values[2]), Kean.Math.Double.Parse(values[3]));
					else if (values.Length == 2)
						result = new Shell(Kean.Math.Double.Parse(values[0]), Kean.Math.Double.Parse(values[1]));
					else if (values.Length == 1)
						result = new Shell(Kean.Math.Double.Parse(values[0]));
				}
				catch
				{
				}
			}
			return result;
		}
		#endregion
		#region Object Overrides
		public override bool Equals(object other)
		{
			return (other is Shell) && this.Equals((Shell)other);
		}
		/// <summary>
		/// Return true if this object and <paramref name="other">other</paramref> are equal.
		/// </summary>
		/// <param name="other">Object to compare with</param>
		/// <returns>True if this object and <paramref name="other">other</paramref> are equal else false.</returns>
		public bool Equals(Shell other)
		{
			return this == other;
		}
		public override int GetHashCode()
		{
			return 33 * (33 * (33 * this.Left.GetHashCode() ^ this.Right.GetHashCode()) ^ this.Top.GetHashCode()) ^ this.Bottom.GetHashCode();
		}
		public override string ToString()
		{
			return (this.Bottom == this.Top && this.Left == this.Right) ? (this.Left == this.Top ? this.ToString("{0}") : this.ToString("{0}, {2}")) : this.ToString("{0}, {1}, {2}, {3}");
		}
		public string ToString(string format)
		{
			return String.Format(format, Kean.Math.Double.ToString(this.Left), Kean.Math.Double.ToString(this.Right), Kean.Math.Double.ToString(this.Top), Kean.Math.Double.ToString(this.Bottom));
		}
		#endregion
	}
}
