// 
//  Point.cs (generated by template)
//  
//  Author:
//       Anders Frisk <andersfrisk77@gmail.com>
//  
//  Copyright (c) 2011-2013 Simon Mika
// 
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
// 
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
// 
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System;
using NUnit.Framework;
using Target = Kean.Math.Geometry3D;
using Kean.Extension;

namespace Kean.Math.Geometry3D.Test.Single
{ 
	[TestFixture]
	public class Point :
		Kean.Test.Fixture<Point>
	   
	{
		float Precision { get { return 1e-4f; } }
		Target.Single.Point CastFromString(string value)
		{
			return value;
		}
		string CastToString(Target.Single.Point value)
		{
			return value;
		}
		
		   Target.Single.Point Point0 = new Target.Single.Point((float)22, (float)-3, (float)10);
		   Target.Single.Point Point1 = new Target.Single.Point((float)12, (float)13, (float)20);
		   Target.Single.Point Point2 = new Target.Single.Point((float)34, (float)10, (float)30);
		   Target.Single.Point Point3 = new Target.Single.Point((float)10, (float)20, (float)30);
		protected override void Run()
		{
		  
			this.Run(
				this.Equality,
				this.Addition,
				this.Subtraction,
				this.ScalarMultitplication,
				this.ScalarProduct,
				this.Casting,
				this.Hash,
				this.Casts,
				this.ValueStringCasts,
				this.Norm
				);
		}
		[Test]
		public void Norm()
		{
			Verify(this.Point0.Norm, Is.EqualTo(24.3515).Within(this.Precision));
		}
		[Test]
		public void ScalarProduct()
		{
			Target.Single.Point point = new Target.Single.Point();
			Verify(this.Point0.ScalarProduct(point), Is.EqualTo(0).Within(this.Precision));
			Verify(this.Point0.ScalarProduct(this.Point1), Is.EqualTo(425).Within(this.Precision));
		}
		[Test]
		public void ScalarMultitplication()
		{
			Verify(this.Point0.VectorProduct(this.Point1), Is.EqualTo(-this.Point1.VectorProduct(this.Point0)));
			Verify((this.Point0.VectorProduct(this.Point1)).X, Is.EqualTo((-190)).Within(this.Precision));
			Verify((this.Point0.VectorProduct(this.Point1)).Y, Is.EqualTo((-320)).Within(this.Precision));
			Verify((this.Point0.VectorProduct(this.Point1)).Z, Is.EqualTo((322)).Within(this.Precision));
		}
		#region Equality
		[Test]
		public void Equality()
		{
#pragma warning disable 1718
			Target.Single.Size point = new Target.Single.Size(); point = null;
			Verify(this.Point0, Is.EqualTo(this.Point0));
			Verify(this.Point0, Is.EqualTo(this.Point0));
			Verify(this.Point0.Equals(this.Point0), Is.True);
			Verify(this.Point0.Equals(this.Point0 as object), Is.True);
			Verify(this.Point0 == this.Point0, Is.True);
			Verify(this.Point0 != this.Point1, Is.True);
			Verify(this.Point0 == point, Is.False);
			Verify(point == point, Is.True);
			Verify(point == this.Point0, Is.False);
#pragma warning restore 1718
		}
		#endregion
		#region Arithmetic
		[Test]
		public void Addition()
		{
			Verify((this.Point0.X + this.Point1.X), Is.EqualTo(this.Point2.X).Within(this.Precision));
			Verify((this.Point0.Y + this.Point1.Y), Is.EqualTo(this.Point2.Y).Within(this.Precision));
			Verify((this.Point0.Z + this.Point1.Z), Is.EqualTo(this.Point2.Z).Within(this.Precision));
		}
		[Test]
		public void Subtraction()
		{
			Target.Single.Size size = new Target.Single.Size(0, 0, 0);
			Target.Single.Size result = this.Point0 - this.Point0;
			Verify(result, Is.EqualTo(size));
		}
		#endregion
		#region Hash Code
		[Test]
		public void Hash()
		{
			Verify(this.Point0.GetHashCode(), Is.Not.EqualTo(0));
		}
		#endregion
		[Test]
		public void Casting()
		{
			string value = "10, 20, 30";
			Verify(this.CastToString(this.Point3), Is.EqualTo(value));
			Verify(this.CastFromString(value), Is.EqualTo(this.Point3));
		}
		 [Test]
		public void Casts()
		{
			// integer - Single
			Target.Integer.Point integer = new Target.Integer.Point(10, 20, 30);
			Target.Single.Point Single = integer;
			Verify(Single.X, Is.EqualTo(10));
			Verify(Single.Y, Is.EqualTo(20));
			Verify(Single.Z, Is.EqualTo(30));
			Verify((Target.Integer.Point)Single, Is.EqualTo(integer));
		}
		 [Test]
		public void ValueStringCasts()
		{
			string textFromValue = new Target.Single.Point(10, 20, 30);
			Verify(textFromValue, Is.EqualTo("10, 20, 30"));
			Target.Single.Point @integerFromText = "10 20 30";
			Verify(@integerFromText.X, Is.EqualTo(10));
			Verify(@integerFromText.Y, Is.EqualTo(20));
			Verify(@integerFromText.Z, Is.EqualTo(30));
		}
				
		

		
		
		
	  }
}
